[alias]
       b = branch
       ba = branch -a
       bd = branch -d
       br = branch -r

       c = commit
       ca = commit -a
       co = checkout

       st = status
[user]
        name = tiand2
        email = david.tian@emc.com
