Vagrant.configure("2") do |config|

	(1..1).each do |i|

		config.vm.define "node#{i}" do |node|

		# 设置虚拟机的Box
		node.vm.box = "ubuntu/xenial64"

		# 设置虚拟机的主机名
		node.vm.hostname="node#{i}"

		# 设置虚拟机的IP
		node.vm.network "private_network", ip: "192.168.10.#{i}"

		# 设置主机与虚拟机的共享目录
		node.vm.synced_folder "~/Desktop/share", "/home/vagrant/share"

		# VirtaulBox相关配置
		node.vm.provider "virtualbox" do |v|

			# 设置虚拟机的名称
			v.name = "node#{i}"

			# 设置虚拟机的内存大小  
			v.memory = 2048

			# 设置虚拟机的CPU个数
			v.cpus = 1
		end

		# 使用shell脚本进行软件安装和配置
		node.vm.provision "shell", inline: <<-SHELL
			groupadd cpsuser
			# encrypted password as "cpsuser"
			useradd cpsuser -g cpsuser -p '$6$HVWx1paP$9dFE7mVH.FK.lsaNqUNw9M.tIuOL4JU.r/lkptmJzYOe1kM38Op8WGyDsC2aXGOXNyOg1t4Vyr3le/xiNBqPD/'
			usermod -aG sudo cpsuser
			mkdir -p /home/cpsuser/
			chown cpsuser:cpsuser /home/cpsuser/
		SHELL
		end
	end
end